template_path: secrets-manager/secret.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  Description: 'bce-training-aurora-cluster-details'
  SecretName: 'bce-training-aurora-cluster-details'
  SecretString: '{"username": "admin", "password": "Password123"}'
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}