template_path: vpc/internet-gateway.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  InternetGatewayName: 'bce-training-ajit-vpc-internet-gateway'
  VpcId: !stack_output bizmaster/vpc/vpc.yaml::Id
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}