template_path: vpc/route-table.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  RouteTableName: 'bce-training-vpc-ajit-private-route-table'
  VpcId: !stack_output bizmaster/vpc/vpc.yaml::Id
hooks:
  after_create:
    - !cmd eval $(sceptre --ignore-dependencies list outputs bizmaster/vpc/route-table-private-subnets.yaml --export=envvar) && echo $SCEPTRE_Id > bizMasterPrivateRouteTableId.txt
  after_update:
    - !cmd eval $(sceptre --ignore-dependencies list outputs bizmaster/vpc/route-table-private-subnets.yaml --export=envvar) && echo $SCEPTRE_Id > bizMasterPrivateRouteTableId.txt
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}