template_path: vpc/route.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  DestinationCidrBlock: '0.0.0.0/0'
  NatGatewayId: !stack_output bizmaster/vpc/nat-gateway.yaml::Id
  RouteTableId: !stack_output bizmaster/vpc/route-table-private-subnets.yaml::Id
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}