template_path: ssm/parameter.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  Description: 'bce training lambda security group - {{ stack_group_config.Environment }}'
  ParamName: '/bce/training/{{ stack_group_config.Environment }}/lambda/security/group'
  ParamValue: !stack_output bizmaster/lambda/security-group.yaml::Id
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}
