template_path: ssm/parameter.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  Description: 'bce training aurora secret arn - {{ stack_group_config.Environment }}'
  ParamName: '/bce/training/{{ stack_group_config.Environment }}/aurora/secret/arn'
  ParamValue: !stack_output bizmaster/aurora/secret.yaml::Arn
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}
