template_path: vpc/nat-gateway.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  NatGatewayName: 'bce-dev-training-vpc-nat-gateway'
  PublicSubnetId: !stack_output bizdev/vpc/public-subnet-a.yaml::Id
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}