template_path: vpc/subnet.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  SubnetName: 'bce-dev-training-private-subnet-b'
  CidrBlock: 10.20.6.0/23
  AvailabilityZone: {{ stack_group_config.AvailabilityZoneB }}
  VpcId: !stack_output bizdev/vpc/vpc.yaml::Id
  RouteTableId: !stack_output bizdev/vpc/route-table-private-subnets.yaml::Id
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}