template_path: vpc/vpc.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  VpcName: 'bce-dev-training-vpc'
  CidrBlock: 10.20.0.0/16
hooks:
  after_create:
    - !cmd eval $(sceptre --ignore-dependencies list outputs bizdev/vpc/vpc.yaml --export=envvar) && echo $SCEPTRE_Id > bizdevVpcId.txt
  after_update:
    - !cmd eval $(sceptre --ignore-dependencies list outputs bizdev/vpc/vpc.yaml --export=envvar) && echo $SCEPTRE_Id > bizdevVpcId.txt
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}