AWSTemplateFormatVersion: "2010-09-09"

Description: Creates an Secrets Manager secret

Parameters:
  Environment:
    Type: String
  Description:
    Type: String
  SecretName:
    Type: String
  SecretString:
    Type: String

Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Ref Description
      Name: !Join ['-', [!Ref SecretName, !Ref Environment]]
      SecretString: !Ref SecretString

Outputs:
  Arn:
    Value: !Ref Secret
  Id:
    Value: !GetAtt Secret.Id