template_path: vpc/route.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  DestinationCidrBlock: '10.20.0.0/16'
  RouteTableId: !file ./bizMasterPublicRouteTableId.txt
  PeeringConnectionId: !stack_output vpc-peering/bizmaster/peering.yaml::Id
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}